apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
  labels:
    app: simple-nodejs-app
spec:
  replicas: 2  # Number of replicas (pods) you want to run
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: rajkumar010/simple-nodejs-app:latest  # Use the image you built (or from Docker)
        ports:
        - containerPort: 3000  # Port your app listens to inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-service
spec:
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 80         # Port for the service (exposed to external traffic)
      targetPort: 3000  # The port on which the application inside the container listens
      nodePort: 30080   # External port on each node in the cluster (range: 30000-32767)
  type: NodePort      # Exposes the service via a port on each node
